# Docker Compose override for development
# This file extends docker-compose.yml with development-specific configurations

version: '3.8'

services:
  backend:
    # Development-specific environment variables
    environment:
      - PYTHONPATH=/app
      - DJANGO_WATCHMAN_TIMEOUT=60
      - DJANGO_AUTORELOAD=1
    # Additional volume mounts for development tools
    volumes:
      - ./backend:/app
      - backend_cache:/app/.cache
    # Override command for development with better debugging
    command: >
      sh -c "echo 'Starting Django development server...' &&
             python manage.py migrate --noinput &&
             python manage.py collectstatic --noinput --clear &&
             python manage.py runserver 0.0.0.0:8000 --noreload"

  frontend:
    # Development-specific environment variables for React
    environment:
      - NODE_ENV=development
      - REACT_APP_API_URL=http://localhost:8000/api
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
      - FAST_REFRESH=true
      - BROWSER=none
      - HOST=0.0.0.0
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - frontend_cache:/app/.cache

  database:
    # Additional logging for development
    environment:
      - POSTGRES_INITDB_ARGS=--encoding=UTF-8 --lc-collate=C --lc-ctype=C
    # Expose logs for debugging
    command: >
      postgres -c log_statement=all
               -c log_destination=stderr
               -c log_min_messages=info
               -c log_min_error_statement=info

volumes:
  backend_cache:
    driver: local
  frontend_cache:
    driver: local